dist: xenial

language: cpp

compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_install:
  - eval "CC=gcc-8 && CXX=g++-8"

install:
  - pip install --user conan

script:
  - conan create external/range-v3 magras/ci
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest --output-on-failure
