dist: xenial

language: cpp

install:
  - pip install --user conan

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest --output-on-failure
